/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.board;

import java.util.Scanner;

public class App {

    static final int SIZE = 3;

    
    

    static int[] no = new int[SIZE];
    static String[] titles= new String[SIZE];
    static String[] contents = new String[SIZE];
    static String[] writers = new String[SIZE];
    static String[] password = new String[SIZE];
    static int[] viewCount = new int[SIZE];
    static long[] createdDate = new long[SIZE];
    static int boardCount = 0;
    static Scanner keyboardInput = new Scanner(System.in);
    
    public static void main(String[] args) {
        welcome();
        loop: while(true) {
            displayMenu();
            int menuNo = promptMenu();
            displayLine();
            switch(menuNo) {
                case 0: break loop;
                case 1: processBoardList(); break;
                case 2: processBoardDetail(); break;
                case 3: processBoardInput(); break;
                default: System.out.println("메뉴 번호가 옳지 않습니다."); break;
            }
        }
    } 

    static void welcome() {
        displayLine();
        System.out.println("[게시판 애플리케이션]");
        System.out.println();
        System.out.println("환영합니다!");
        System.out.println();
        displayLine();
    }

    static void processBoardList() {
        System.out.println("[게시글 목록]");
        System.out.println("번호 제목 조회수 작성자 등록일");

        for(int i = 0; i < boardCount; i++) {
            java.util.Date date = new java.util.Date(createdDate[i]);

            // 날짜 정보에서 값을 추출하여 특정 포맷의 문자열로 만들어줄 도구를 준비 
            java.text.SimpleDateFormat df =
              new java.text.SimpleDateFormat("yyyy-MM-dd");
            String dateStr = df.format(date);
            
            System.out.printf("%d\t%s\t%d\t%s\t%s\n",
              no[i], titles[i], viewCount[i], writers[i], dateStr);
        }
    }

    static void processBoardDetail() {
        System.out.println("게시판 상세보기");
        System.out.printf("조회할 게시글 번호? ");
        
        String input = keyboardInput.nextLine();
        int boardNo = Integer.parseInt(input);
        
        int boardIndex = -1;
        for (int i=0; i< boardCount; i++) {
            if (no[i] == boardNo) {
                boardIndex = i;
                break;
            }
        }
        
        // 사용자가 입력한 번호에 해당하는 게시글을 못찾았다면
        if (boardIndex == -1) {
            System.out.println("해당 번호의 게시글이 없습니다!");
            return;
        }
                
        System.out.printf("번호 : %d\n", no[boardIndex]);  
        System.out.printf("제목 : %s\n", titles[boardIndex]);
        System.out.printf("내용 : %s\n", contents[boardIndex]);
        System.out.printf("조회수 : %d\n", viewCount[boardIndex]);
        System.out.printf("작성자 : %s\n", writers[boardIndex]);
        java.util.Date date = new java.util.Date(createdDate[boardNo]);
        System.out.printf("등록일 : %tY-%1$tm-%1$td\n", date);
    }

    static void processBoardInput() {
        System.out.println("[게시글 등록]");

        // 배열의 크기를 초과하지 않았는지 검사한다.
        if (boardCount == SIZE) {
            System.out.println("게시글의 최대 개수를 초과했습니다!");
            return;
        }

        System.out.println("제목? ");
        titles[boardCount] = keyboardInput.nextLine();

        System.out.println("내용? ");
        contents[boardCount] = keyboardInput.nextLine();

        System.out.println("제목?");
        writers[boardCount] = keyboardInput.nextLine();

        System.out.println("암호? ");
        password[boardCount] = keyboardInput.nextLine();
        
        no[boardCount] = boardCount == 0 ? 1:  no[boardCount - 1] + 1;
        viewCount[boardCount] = 0;
        createdDate[boardCount] = System.currentTimeMillis();

        boardCount++;
    }

    static void displayMenu() {
        System.out.println("메뉴:");
            System.out.println("  1. 게시글 목록");
            System.out.println("  2. 게시글 상세보기");
            System.out.println("  3. 게시글 등록");
            System.out.println();
            System.out.printf("메뉴를 선택하세요[1..3](0.종료) ");
    }

    static void displayLine() {
        System.out.println("------------------------");
    }

    static int promptMenu() {
        int menuNo = keyboardInput.nextInt();
        keyboardInput.nextLine();
        return menuNo;
    }
    static void displayBlankLine() {
        System.out.println();
    }
}
