/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.board;

public class App {
    public String getGreeting() {
        return "자바 게시판";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
