/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.board;

public class App {

  public static void main(String[] args) {

    Fundamental.welcome();
    //Fundamental.Login();
    loop: while(true) {
      // 메인 메뉴 출력
      System.out.println("게시판: ");
      System.out.println("  1. 게시판");
      System.out.println("  2. 독서록");
      System.out.println("  3. 방명록");
      System.out.println("  4. 공지사항");
      System.out.println();

      int  mainMenuNo = Prompt.inputInt("메뉴를 선택하세요[1..4](0.종료) ");
      switch(mainMenuNo) {
        case 0: break loop;
        case 1: BoardHandler.execute(); break; // 게시판
        case 2: ReadingHandler.execute(); break; // 독서록2
        case 3: VisitHandler.execute(); break;// 방명록
        case 4: NoticeHandler.execute(); break;// 공지사항
        default: System.out.println("메뉴 번호가 옳지 않습니다."); break;
      }
    }

  }

}
